# Generated by Django 3.1.4 on 2020-12-10 18:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^m[0-9]{1,9}$')])),
                ('name', models.CharField(max_length=150)),
                ('weight', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('about_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mediadisplaypage')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('module_id', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ModuleSubsections',
            fields=[
                ('subsection_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('about_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mediadisplaypage')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.modules')),
            ],
        ),
        migrations.CreateModel(
            name='SubsectionPages',
            fields=[
                ('join_id', models.AutoField(primary_key=True, serialize=False)),
                ('block_id', models.CharField(max_length=150)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.pages')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.modulesubsections')),
            ],
            options={
                'unique_together': {('page', 'subsection')},
            },
        ),
        migrations.CreateModel(
            name='ModuleUsers',
            fields=[
                ('join_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=40)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.modules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
    ]
