# Generated by Django 3.1.4 on 2020-12-10 18:09

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/files/media'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/files/pages'), upload_to='')),
                ('date_stored', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaDisplayPage',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.pages')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionDisplayPage',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.pages')),
                ('max_mark', models.IntegerField(null=True)),
                ('expected_duration', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileSubmissionPage',
            fields=[
                ('submission_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.submissiondisplaypage')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSubmissionPage',
            fields=[
                ('submission_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.submissiondisplaypage')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('join_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.IntegerField(null=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/files/answers'), upload_to='')),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.submissiondisplaypage')),
            ],
            options={
                'unique_together': {('user', 'submission_page')},
            },
        ),
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('join_id', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pages')),
                ('media_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.mediadisplaypage')),
            ],
            options={
                'unique_together': {('page', 'media_page')},
            },
        ),
    ]
