# Generated by Django 3.1.4 on 2020-12-10 18:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^c[0-9]{1,9}$')])),
                ('name', models.CharField(max_length=150)),
                ('max_students', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('about_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mediadisplaypage')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('join_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
