# Generated by Django 3.1.4 on 2020-12-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
